export const clubs = [
    {
      name: "Shoolini Creative Studio",
      type: "sports",
      tags: ["outdoor", "team", "active"],
      president:"rohit",
      contact: "919913123987124",
      img: "images/shoolinicreativestudio.jpeg",
      description: "Shoolini Creative Studio is the performance arts and theatre ensemble of Shoolini University,Himachal Pradesh. Its intention is to build a cultural community ofvisionaries, actors, film makersartists, musicians, dancers, poets,architects and designers in Shoolini University. It organizes mega theatre productions."
      
    },
    {
      name: "Raag Rang Club",
      type: "arts",
      tags: ["creative", "indoor", "expressive"],
      img: "images/raagrang.png",
    },
    {
      name: "Satrangi Strokes",
      type: "tech",
      tags: ["innovation", "programming", "engineering"],
      img: "images/satrangistrokes.jpg",
    },
    {
      name: "Saksham Dance Club",
      type: "community",
      tags: ["helping", "social work", "volunteering"],
      img: "images/sakshamdanceclub.jpg",
    },
    {
      name: "Cinedicate-The Filmmaking Club",
      type: "arts",
      tags: ["camera", "creativity", "outdoor"],
      img: "images/filmclub.jpg",
    },
    {
      name: "Himshobla Club",
      type: "sports",
      tags: ["outdoor", "team", "active"],
      img: "images/Himshobla.jpeg",
    },
    {
      name: "Loudspeakers Club",
      type: "tech",
      tags: ["strategy", "indoor", "intellect"],
      img: "images/loudspeakerclub.jpeg",
    },
    {
      name: "Prism Club",
      type: "tech",
      tags: ["programming", "coding", "hackathons"],
      img: "images/prism.jpeg",
    },
    {
      name: "Genomage Club",
      type: "arts",
      tags: ["acting", "stage", "performance"],
      img: "images/Genomage.jpeg",
    },
    {
      name: "Bosh Music Club",
      type: "arts",
      tags: ["instruments", "vocals", "performance"],
      img: "images/musicclub.jpg",
    },
    {
      name: "Animal Lovers Club",
      type: "sports",
      tags: ["outdoor", "nature", "adventure"],
      img: "images/animalloverclub.png",
    },
    {
      name: "YCC Club",
      type: "community",
      tags: ["speaking", "logic", "debate"],
      img: "images/yccclub.jpg",
    },
    {
      name: "Lit Witz Club",
      type: "community",
      tags: ["nature", "environment", "activism"],
      img: "images/litwitzclub.jpg",
    },
    {
      name: "The Red Taboos Club",
      type: "tech",
      tags: ["video games", "competitive", "fun"],
      img: "images/redtaboosclub.png",
    },
    {
      name: "Cuisine Club",
      type: "arts",
      tags: ["choreography", "performance", "creative"],
      img: "images/cuisineclub.jpeg",
    },
    {
      name: "Drishyam Club",
      type: "sports",
      tags: ["wellness", "meditation", "health"],
      img: "images/drishyamclub.jpg",
    },
    {
      name: "Sanchay:Maths Club",
      type: "sports",
      tags: ["self-defense", "training", "discipline"],
      img: "images/sanchaymathsclub.jpeg",
    },
    {
      name: "Vision Threads Club",
      type: "arts",
      tags: ["clothing", "design", "creative"],
      img: "images/visionthreadclub.jpeg",
    },
    {
      name: "Environment and Sustainability Club",
      type: "arts",
      tags: ["reading", "writing", "poetry"],
      img: "images/environmentclub.jpg",
    },
    {
      name: "Hackhound (Cybersecurity Club)",
      type: "tech",
      tags: ["stars", "space", "science"],
      img: "images/hackhoundclub.jpg",
    },
    {
      name: "Shakerz Skaterz",
      type: "community",
      tags: ["films", "reviews", "cinema"],
      img: "images/skaters.jpg",
    },
    {
      name: "Antarmada",
      type: "sports",
      tags: ["water", "fitness", "team"],
      img: "images/antarmadaclub.jpg",
    },
    {
      name: "Arcadia Club",
      type: "sports",
      tags: ["fitness", "outdoor", "cycling"],
      img: "images/arcadia.jpg",
    },
    {
      name: "Weeb Club",
      type: "community",
      tags: ["helping", "fundraising", "social work"],
      img: "images/weebclub.jpg",
    },
    {
      name: "Katha",
      type: "tech",
      tags: ["numbers", "problem-solving", "science"],
      img: "images/kathaclub.jpg",
    },
    {
      name: "Mountain Rangers",
      type: "community",
      tags: ["reading", "discussion", "literature"],
      img: "images/mountainranger.png",
    },
    {
      name: "Pedals Cycling Club",
      type: "tech",
      tags: ["experiments", "research", "discovery"],
      img: "images/cyclingclub.jpg",
    },
    {
      name: "Ounce Motorsports",
      type: "arts",
      tags: ["gallery", "critique", "creativity"],
      img: "images/motorsports.jpg",
    },
    {
      name: "Joypad Symphony",
      type: "community",
      tags: ["food", "recipes", "cooking"],
      img: "images/joypad_symphony.jpg",
    },
    {
      name: "IIC (Institution Innovation Council)",
      type: "community",
      tags: ["speech", "confidence", "leadership"],
      img: "images/iic.jpg",
    },
    {
      name: "Deez Knights Chess Club",
      type: "community",
      tags: ["speech", "confidence", "leadership"],
      img: "images/deez_knights_chess_club.jpg",
    },
    {
      name: "Student Research Council Shoolini",
      type: "community",
      tags: ["speech", "confidence", "leadership"],
      img: "images/student_research_council.jpg",
    },
    {
      name: "IEEE Shoolini Student Branch",
      type: "community",
      tags: ["speech", "confidence", "leadership"],
      img: "images/ieee_shoolini.jpg",
    },
    {
      name: "ACM Student Chapter",
      type: "community",
      tags: ["speech", "confidence", "leadership"],
      img: "images/acm_student_chapter.jpg",
    },
  ];