export const clubs = [
    {
      name: "Shoolini Creative Studio",
      type: "sports",
      tags: ["outdoor", "team", "active"],
      img: "images/caps.jpg",
      description: "Shoolini Creative Studio is the performance arts and theatre ensemble of Shoolini University,Himachal Pradesh. Its intention is to build a cultural community ofvisionaries, actors, film makersartists, musicians, dancers, poets,architects and designers in Shoolini University. It organizes mega theatre productions."
      
    },
    {
      name: "Raag Rang Club",
      type: "arts",
      tags: ["creative", "indoor", "expressive"],
      img: "images/shoolini campus.jpg",
    },
    {
      name: "Satrangi Strokes",
      type: "tech",
      tags: ["innovation", "programming", "engineering"],
      img: "images/f-logo.png",
    },
    {
      name: "Saksham Dance Club",
      type: "community",
      tags: ["helping", "social work", "volunteering"],
      img: "images/logo.png",
    },
    {
      name: "Cinedicate-The Filmmaking Club",
      type: "arts",
      tags: ["camera", "creativity", "outdoor"],
      img: "images/Uni_students_-_Main.pngcinedicate_filmmaking_club.jpg",
    },
    {
      name: "Himshobla Club",
      type: "sports",
      tags: ["outdoor", "team", "active"],
      img: "images/oat.jpg",
    },
    {
      name: "Loudspeakers Club",
      type: "tech",
      tags: ["strategy", "indoor", "intellect"],
      img: "images/temple.jpg",
    },
    {
      name: "Prism Club",
      type: "tech",
      tags: ["programming", "coding", "hackathons"],
      img: "images/badminton.jpg",
    },
    {
      name: "Genomage Club",
      type: "arts",
      tags: ["acting", "stage", "performance"],
      img: "images/genomage_club.jpg",
    },
    {
      name: "Bosh Music Club",
      type: "arts",
      tags: ["instruments", "vocals", "performance"],
      img: "images/bosh_music_club.jpg",
    },
    {
      name: "Animal Lovers Club",
      type: "sports",
      tags: ["outdoor", "nature", "adventure"],
      img: "images/animal_lovers_club.jpg",
    },
    {
      name: "YCC Club",
      type: "community",
      tags: ["speaking", "logic", "debate"],
      img: "images/ycc_club.jpg",
    },
    {
      name: "Lit Witz Club",
      type: "community",
      tags: ["nature", "environment", "activism"],
      img: "images/lit_witz_club.jpg",
    },
    {
      name: "The Red Taboos Club",
      type: "tech",
      tags: ["video games", "competitive", "fun"],
      img: "images/red_taboos_club.jpg",
    },
    {
      name: "Cuisine Club",
      type: "arts",
      tags: ["choreography", "performance", "creative"],
      img: "images/cuisine_club.jpg",
    },
    {
      name: "Drishyam Club",
      type: "sports",
      tags: ["wellness", "meditation", "health"],
      img: "images/drishyam_club.jpg",
    },
    {
      name: "Sanchay:Maths Club",
      type: "sports",
      tags: ["self-defense", "training", "discipline"],
      img: "images/sanchay_maths_club.jpg",
    },
    {
      name: "Vision Threads Club",
      type: "arts",
      tags: ["clothing", "design", "creative"],
      img: "images/vision_threads_club.jpg",
    },
    {
      name: "Environment and Sustainability Club",
      type: "arts",
      tags: ["reading", "writing", "poetry"],
      img: "images/environment_sustainability_club.jpg",
    },
    {
      name: "Hackhound (Cybersecurity Club)",
      type: "tech",
      tags: ["stars", "space", "science"],
      img: "images/hackhound_cybersecurity_club.jpg",
    },
    {
      name: "Shakerz Skaterz",
      type: "community",
      tags: ["films", "reviews", "cinema"],
      img: "images/shakerz_skaterz.jpg",
    },
    {
      name: "Antarmada",
      type: "sports",
      tags: ["water", "fitness", "team"],
      img: "images/antarmada.jpg",
    },
    {
      name: "Arcadia Club",
      type: "sports",
      tags: ["fitness", "outdoor", "cycling"],
      img: "images/arcadia_club.jpg",
    },
    {
      name: "Weeb Club",
      type: "community",
      tags: ["helping", "fundraising", "social work"],
      img: "images/weeb_club.jpg",
    },
    {
      name: "Katha",
      type: "tech",
      tags: ["numbers", "problem-solving", "science"],
      img: "images/katha.jpg",
    },
    {
      name: "Mountain Rangers",
      type: "community",
      tags: ["reading", "discussion", "literature"],
      img: "images/mountain_rangers.jpg",
    },
    {
      name: "Pedals Cycling Club",
      type: "tech",
      tags: ["experiments", "research", "discovery"],
      img: "images/pedals_cycling_club.jpg",
    },
    {
      name: "Ounce Motorsports",
      type: "arts",
      tags: ["gallery", "critique", "creativity"],
      img: "images/ounce_motorsports.jpg",
    },
    {
      name: "Joypad Symphony",
      type: "community",
      tags: ["food", "recipes", "cooking"],
      img: "images/joypad_symphony.jpg",
    },
    {
      name: "IIC (Institution Innovation Council)",
      type: "community",
      tags: ["speech", "confidence", "leadership"],
      img: "images/iic.jpg",
    },
    {
      name: "Deez Knights Chess Club",
      type: "community",
      tags: ["speech", "confidence", "leadership"],
      img: "images/deez_knights_chess_club.jpg",
    },
    {
      name: "Student Research Council Shoolini",
      type: "community",
      tags: ["speech", "confidence", "leadership"],
      img: "images/student_research_council.jpg",
    },
    {
      name: "IEEE Shoolini Student Branch",
      type: "community",
      tags: ["speech", "confidence", "leadership"],
      img: "images/ieee_shoolini.jpg",
    },
    {
      name: "ACM Student Chapter",
      type: "community",
      tags: ["speech", "confidence", "leadership"],
      img: "images/acm_student_chapter.jpg",
    },
  ];